// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { foregroundStyle: 'white', frontID: 'front', onclick: 'showSettings', backgroundStyle: 'black' });
    CreateGlassButton('done', { onclick: 'saveSettings', text: 'Fertig' });
    CreateText('text', { text: 'URL:' });
    CreateText('text1', { text: 'Username:' });
    CreateText('text2', { text: 'Password:' });
    CreateText('text3', { text: 'What are you working on?' });
    CreateButton('button', { text: 'Update', onclick: 'updateStatus', rightImageWidth: 10, leftImageWidth: 10 });
    CreateScrollArea('statuses', { hasVerticalScrollbar: true, scrollbarDivSize: 18, autoHideScrollbars: true, scrollbarMargin: 6 });
    CreateText('text4', { text: 'brought to you by railslove.com' });
}
window.addEventListener('load', setupParts, false);
